junit:
  stage: test
  script:
    - mvn -B clean test

recent-artifacts:
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  except:
    - tags

release-artifacts:
  stage: deploy
  script:
    - mvn -B clean site package
  artifacts:
    paths:
    - target/*.jar
  only:
    - tags
