tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

junit:
  stage: test
  script:
    - sbt test

recent-artifacts:
  stage: deploy
  script:
    - sbt dist
  artifacts:
    paths:
      - target/universal/*.zip
    expire_in: 1 week
  except:
    - tags

release-artifacts:
 stage: deploy
 script:
    - sbt dist
 artifacts:
    paths:
    - target/universal/*.zip
 only:
    - tags

start-server-dev:
  stage: deploy
  script:
    - sbt dist
    - travelEAdev stop
    - sudo rm -d -r /opt/server-dev/**
    - sudo unzip target/universal/*.zip -d /opt/server-dev/
    - travelEAdev start
  only:
    - master-dev@seng302-2019/team-400
    - dedicated@seng302-2019/team-400

start-server-prod:
  stage: deploy
  script:
  - sbt "run 443"
  only:
    - master@seng302-2019/team-400

Update-sonar:
  stage: deploy
  script:
    - sbt compile && sbt checkstyle && sonar-scanner
  only:
    - master@seng302-2019/team-400
    - master-dev@seng302-2019/team-400
